### ISSUE TITLE
Installer

### ISSUE THREAD

**Issue by xmha97** [ALIILAPRO/dns-changer#1]
Hi, thanks for this app.
Please make an installer (setup).

**Comment by ALIILAPRO** [comment]
> Hi, thanks for this app. Please make an installer (setup).

Hi. You're welcome. It will be added in the next version.

**Comment by xmha97** [comment]
> > Hi, thanks for this app. Please make an installer (setup).
> 
> Hi. You're welcome. It will be added in the next version.

Thanks <3

**Comment by xmha97** [comment]
Please release a new version.

**Comment by xmha97** [comment]
درود
برنامه هنوز هم اینستالر ندارد
منظورم از اینستالر، اینستالر پیشفرض اپلیکیشن‌ها نیست (NSIS)
از آنجایی که برنامه پرتابل است، اصلا منطقی هم نیست که چنین کاری انجام شود
می‌توانید در اولین اجرا مسیج باکسی به کاربر نمایش دهید در خصوص نصب برنامه و اگر کاربر تایید کرد، برنامه کپی بشه در AppData و شورت‌کاتی هم در استارت منو گذاشته شود
